### PR TITLE
Fix for issue #52

### PR DESCRIPTION
**Pull request by robermann**
Issue #52: "Saving with title as name overwrites files when multiple images have same title".

When a file is already present in the directory, we add now a counter so that the new file name is unique.

### CODE REVIEW

**Comment by floydpink** [comment]
Thanks for the PR - I will review it in the next couple of days and let you know if it can be merged.

**Comment by robermann** [comment]
Yes correct, my pull request should have contained only that commit (I submitted it even before committing the other changes). 

By the way, if you are interested, lately I've added two new features:

- an option to name the pictures according Flickr's order inside an album
- an option to search for albums whose name matches a filter (I have 4K+ albums and cannot search by just pagination)

Both the above options have been added into the Preferences panel.

**Comment by robermann** [comment]
(see my new pull request for just the fix)

**Comment by robermann** [comment]
See my next pull request for a new download option.

**Pull request closed without merging**
